# Generated by Django 3.2 on 2022-01-30 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import registers.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crud', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=600, unique=True, verbose_name='Descripción')),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes', validators=[registers.validators.valid_extension], verbose_name='')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('status', models.BooleanField(default=True, help_text='Indica si el registro está Activo o Inactivo.', verbose_name='Activo')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('sub_category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crud.subcategory', verbose_name='Sub Categoría')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
                'ordering': ['create_date'],
            },
        ),
    ]
