# Generated by Django 3.2 on 2021-09-12 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=600, unique=True, verbose_name='Descripción')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('status', models.BooleanField(default=True, help_text='Indica si el registro está Activo o Inactivo.', verbose_name='Activo')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('sub_category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crud.subcategory', verbose_name='Sub Categoría')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='CodeQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_code', models.CharField(max_length=200, unique=True, verbose_name='Código QR')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('registre', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='registers.register', verbose_name='Registro')),
            ],
            options={
                'verbose_name': 'Código QR',
                'verbose_name_plural': 'Códigos QR',
                'ordering': ['-create_date'],
            },
        ),
    ]
