# Generated by Django 3.2 on 2022-01-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
        migrations.DeleteModel(
            name='CodeQR',
        ),
    ]
