# Generated by Django 3.2 on 2021-05-25 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='registration_date',
            field=models.DateField(verbose_name='Fecha de Registro'),
        ),
    ]
