# Generated by Django 3.2 on 2021-05-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0002_alter_register_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='registration_date',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Registro'),
        ),
    ]
