# Generated by Django 3.2 on 2021-06-05 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0003_alter_register_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='sub_category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='registers.subcategory', verbose_name='Sub Categoría'),
        ),
    ]
