# Generated by Django 3.2 on 2022-01-20 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0003_alter_register_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='qr_code',
        ),
    ]
