# Generated by Django 3.2 on 2022-01-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0004_remove_register_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
    ]
