# Generated by Django 3.2 on 2022-01-26 20:43

from django.db import migrations, models
import registers.validators


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0006_alter_register_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes', validators=[registers.validators.valid_extension]),
        ),
    ]
