# Generated by Django 3.2 on 2021-09-12 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=600, unique=True, verbose_name='Descripción')),
                ('found_date', models.DateField(default='2021-09-12', verbose_name='Fecha')),
                ('found_time', models.TimeField(default='19:35', verbose_name='Hora')),
                ('image', models.ImageField(upload_to='reports', verbose_name='Imagen')),
                ('status', models.BooleanField(default=True, help_text='Indica si el registro está Activo o Inactivo.', verbose_name='Activo')),
                ('coord_latitude', models.CharField(max_length=50, verbose_name='Coordenada Latitud')),
                ('coord_length', models.CharField(max_length=50, verbose_name='Coordenada Longitud')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('sub_category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crud.subcategory', verbose_name='Sub Categoría')),
                ('type_report', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crud.typereport', verbose_name='Tipo de Reporte')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-create_date'],
            },
        ),
    ]
