# Generated by Django 3.2 on 2022-01-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='found_date',
            field=models.DateField(default='2022-01-31', verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='report',
            name='found_time',
            field=models.TimeField(default='20:02', verbose_name='Hora'),
        ),
    ]
