# Generated by Django 3.2 on 2021-09-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='found_time',
            field=models.TimeField(default='19:36', verbose_name='Hora'),
        ),
    ]
