# Generated by Django 3.2 on 2021-08-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='c_latitude',
            new_name='coord_latitude',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='c_length',
            new_name='coord_length',
        ),
        migrations.AlterField(
            model_name='report',
            name='found_time',
            field=models.TimeField(default='22:02', verbose_name='Hora'),
        ),
    ]
