# Generated by Django 3.2 on 2021-08-16 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='found_date',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha Encontrada'),
        ),
        migrations.AlterField(
            model_name='report',
            name='found_time',
            field=models.TimeField(auto_now_add=True, verbose_name='Hora Encontrada'),
        ),
    ]
