# Generated by Django 3.2 on 2022-02-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20220131_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='found_date',
            field=models.DateField(default='2022-02-07', verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='report',
            name='found_time',
            field=models.TimeField(default='18:31', verbose_name='Hora'),
        ),
    ]
