# Generated by Django 3.2 on 2021-08-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20210815_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='found_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha Encontrada'),
        ),
        migrations.AlterField(
            model_name='report',
            name='found_time',
            field=models.TimeField(auto_now=True, verbose_name='Hora Encontrada'),
        ),
    ]
