# Generated by Django 3.2.3 on 2022-01-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20220103_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='found_time',
            field=models.TimeField(default='22:01', verbose_name='Hora'),
        ),
    ]
