# Generated by Django 3.2 on 2021-08-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20210815_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='found_date',
            field=models.DateField(verbose_name='Fecha Encontrada'),
        ),
        migrations.AlterField(
            model_name='report',
            name='found_time',
            field=models.TimeField(verbose_name='Hora Encontrada'),
        ),
    ]
