# Generated by Django 3.2 on 2022-03-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20220211_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reward',
            field=models.CharField(default=0, max_length=1000, verbose_name='Recompensa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='found_date',
            field=models.DateField(default='2022-03-17', verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='report',
            name='found_time',
            field=models.TimeField(default='20:57', verbose_name='Hora'),
        ),
    ]
