# Generated by Django 3.2.3 on 2022-01-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_report_found_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='found_time',
            field=models.TimeField(default='22:02', verbose_name='Hora'),
        ),
    ]
