# Generated by Django 3.2 on 2022-01-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_report_found_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='found_date',
            field=models.DateField(default='2022-01-20', verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='report',
            name='found_time',
            field=models.TimeField(default='14:02', verbose_name='Hora'),
        ),
    ]
