# Generated by Django 3.2 on 2022-03-18 12:51

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20220317_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='found_date',
            field=models.DateField(default='2022-03-18', verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='report',
            name='found_time',
            field=models.TimeField(default='12:51', verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reward',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='Recompensa'),
        ),
    ]
