# Generated by Django 3.2 on 2022-01-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20220120_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='found_time',
            field=models.TimeField(default='14:21', verbose_name='Hora'),
        ),
    ]
