# Generated by Django 3.2 on 2022-01-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_report_found_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='found_time',
            field=models.TimeField(default='14:39', verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.ImageField(default=None, upload_to='reports', verbose_name='Imagen'),
        ),
    ]
