# Generated by Django 3.2 on 2022-01-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20220120_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-create_date'], 'verbose_name': 'Reporte', 'verbose_name_plural': 'Reportes'},
        ),
        migrations.AlterField(
            model_name='report',
            name='found_time',
            field=models.TimeField(default='20:28', verbose_name='Hora'),
        ),
    ]
