# Generated by Django 3.2 on 2022-01-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_auto_20220120_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='found_time',
            field=models.TimeField(default='20:32', verbose_name='Hora'),
        ),
    ]
