# Generated by Django 3.2 on 2022-01-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_alter_report_found_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='found_date',
            field=models.DateField(default='2022-01-21', verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='report',
            name='found_time',
            field=models.TimeField(default='08:36', verbose_name='Hora'),
        ),
    ]
