# Generated by Django 3.2 on 2022-01-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_auto_20220126_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='found_time',
            field=models.TimeField(default='20:43', verbose_name='Hora'),
        ),
    ]
