# Generated by Django 3.2 on 2022-01-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_alter_report_found_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='found_time',
            field=models.TimeField(default='20:45', verbose_name='Hora'),
        ),
    ]
