# Generated by Django 3.2 on 2021-06-08 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crud', '0002_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_document', models.CharField(max_length=50, verbose_name='Número de Documento')),
                ('names', models.CharField(max_length=200, verbose_name='Nombres')),
                ('last_names', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('birthday', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('phone', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('direction', models.CharField(max_length=200, verbose_name='Domicilio')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('city', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crud.city', verbose_name='Ciudad')),
                ('country', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crud.country', verbose_name='País')),
                ('departament', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crud.departament', verbose_name='Departamento')),
                ('sexe', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crud.sexe', verbose_name='Sexo')),
                ('type_document', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crud.typedocument', verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profiles')),
                ('bio', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True)),
                ('person', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='registration.person', verbose_name='Persona')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
