# Generated by Django 3.2 on 2021-06-08 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='numer_document',
            new_name='number_document',
        ),
        migrations.AlterField(
            model_name='profile',
            name='person',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='registration.person', verbose_name='Persona'),
        ),
    ]
