# Generated by Django 3.2 on 2022-02-07 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
        ('registration', '0002_auto_20220131_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(default=0, help_text='Seleccione su Fecha de Nacimiento', verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.ForeignKey(default=0, help_text='Seleccione su Ciudad', on_delete=django.db.models.deletion.CASCADE, to='crud.city', verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='person',
            name='country',
            field=models.ForeignKey(default=0, help_text='Seleccione su País', on_delete=django.db.models.deletion.CASCADE, to='crud.country', verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='person',
            name='departament',
            field=models.ForeignKey(default=0, help_text='Seleccione su Departamento', on_delete=django.db.models.deletion.CASCADE, to='crud.departament', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='person',
            name='direction',
            field=models.CharField(help_text='Ingrese su Dirección', max_length=200, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(help_text='Ingrese su Apellido', max_length=200, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(help_text='Ingrese su Nombre', max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(help_text='Ingrese su Teléfono', max_length=50, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sexe',
            field=models.ForeignKey(default=0, help_text='Seleccione su Sexo', on_delete=django.db.models.deletion.CASCADE, to='crud.sexe', verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.person'),
        ),
    ]
