# Generated by Django 3.2 on 2022-03-19 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0007_auto_20220319_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='receiver',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='transmitter',
            field=models.CharField(default=1, help_text='Ingrese su Nombre', max_length=200, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
