# Generated by Django 3.2 on 2022-03-19 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20220319_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.person'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='transmitter',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
    ]
