# Generated by Django 3.2 on 2022-03-19 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20220319_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 3, 19, 15, 35, 42, 233131), verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False, help_text='Indica si el mensaje ha sido leído o no.', verbose_name='Leído'),
        ),
    ]
