# Generated by Django 3.2 on 2021-05-24 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, unique=True, verbose_name='Descripción')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, unique=True, verbose_name='Descripción')),
                ('nacionality', models.CharField(max_length=200, unique=True, verbose_name='Nacionalidad')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, unique=True, verbose_name='Descripción')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='Sexe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, unique=True, verbose_name='Descripción')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Sexo',
                'verbose_name_plural': 'Sexos',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, unique=True, verbose_name='Descripción')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='TypeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, unique=True, verbose_name='Descripción')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Tipo de Reporte',
                'verbose_name_plural': 'Tipos de Reportes',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=600, unique=True, verbose_name='Descripción')),
                ('found_date', models.DateField(verbose_name='Fecha Encontrada')),
                ('found_time', models.TimeField(verbose_name='Hora Encontrada')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Imagen')),
                ('status', models.BooleanField(default=True, help_text='Indica si el registro está Activo o Inactivo.', verbose_name='Activo')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('type_report', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crud.typereport', verbose_name='Tipo de Reporte')),
                ('usser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_document', models.CharField(max_length=50, verbose_name='Número de Documento')),
                ('names', models.CharField(max_length=200, verbose_name='Nombres')),
                ('surnames', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('birthday', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('phone', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('direction', models.CharField(max_length=200, verbose_name='Domicilio')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('city', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crud.city', verbose_name='Ciudad')),
                ('country', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crud.country', verbose_name='País')),
                ('departament', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crud.departament', verbose_name='Departamento')),
                ('sexe', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crud.sexe', verbose_name='Sexo')),
                ('type_document', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crud.typedocument', verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_latitude', models.FloatField(verbose_name='Latitud')),
                ('c_length', models.FloatField(verbose_name='Longitud')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('report', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crud.report', verbose_name='Reporte')),
            ],
            options={
                'verbose_name': 'Coordenada',
                'verbose_name_plural': 'Coordenadas',
                'ordering': ['-create_date'],
            },
        ),
    ]
