# Generated by Django 3.2 on 2021-08-16 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='type_report',
        ),
        migrations.RemoveField(
            model_name='report',
            name='usser',
        ),
        migrations.DeleteModel(
            name='Coordinate',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='TypeReport',
        ),
    ]
