# Generated by Django 3.2 on 2022-02-11 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TypeDocument',
        ),
    ]
