# Generated by Django 3.2 on 2021-05-21 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_auto_20210520_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='Imagen'),
        ),
    ]
